### ISSUE TITLE
Backstories.xml

### ISSUE THREAD

**Issue by Laoka25** [Ludeon/RimWorld-Hungarian#82]
I can't delete the Line 4016 (empty line)from backstories.xml

Line 4016 cause errors in backstory translation.

**Comment by pluhi** [comment]
Szia, nyugodtan írj magyarul, más nem nézi ezt. Milyen error?

**Comment by Laoka25** [comment]
Oké. Szóval mikor megnyitom a játékot, akkor a dev logban azt olvashatom, hogy nem sikerült lefordítani a háttértörténetet

**Comment by Laoka25** [comment]
És rájöttem, hogyha kitörölóm az utolsó sort, akkor viszont minden jól működik

**Comment by Laoka25** [comment]
Mármint a backstories.xml utolsó (4016.) üres sorát, de ezt gitHub on valamiért nem tudom megcsinálni, magától csinál egy üres sort a legvégére

**Comment by Laoka25** [comment]
Akkor nincs gond, mert én meg tudom magamnak oldani, ha másnak meg működik, akkor tényleg nincs gond

**Comment by Laoka25** [comment]
![](https://i.imgur.com/Bu42LUT.png)

**Comment by pluhi** [comment]
Ez nagyon fura, nálam már a HeDiffDef error sincs, ez a sor ki kellene legyen commentelve a Hediffs_Local_AddedParts.xml-ben. A backstory is simán betöltődik, van a fájlban 4016-os sor.

**Comment by Laoka25** [comment]
Nem tudom akkor mitől lehet

**Comment by pluhi** [comment]
Milyen verziód van? Steames? Mi a verziószám?
